# Generated by Django 5.0.6 on 2024-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavelet_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='images/compressed/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
